# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# INFO:
# Analyse the clustering generated by a specific resolution.
# Take:
#   06_seurat.rds
# Store:
#   07_cluster_markers.rds
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Packages
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
library("tidyverse")
library("Seurat")
library("yaml")
library("naturalsort")
library("reshape2")
library("semla")
library("presto")

# bioc
library("BiocParallel")
library("org.Hs.eg.db")
library("clusterProfiler")

source("code/helper/FG_modulescores_helper.R")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
manifest = yaml.load_file("assets/manifest.yaml")
all_samples = c(manifest$samples, manifest$external_samples)
random_seed = 1234

for (sample_id in all_samples) {

  print(paste("Active sample is now:", sample_id))
  sample_manifest = manifest[[sample_id]]
  work.dir = file.path(manifest$workdata_parent, sample_manifest$workdata)

  se = readRDS(file.path(work.dir, "06_seurat.rds"))

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Cluster markers
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  cl.res = paste0("SCT_snn_res.", sample_manifest$seurat_clustering_resolution)
  se$seurat_clusters = se[[cl.res]]
  Idents(se) = "seurat_clusters"
  DefaultAssay(se) = "Spatial"

  dgea.pvalue = 0.01
  # min.pct = 0.5 and logfc.threshold = 0.50 are specific expression filter (not a good solution)
  min.pct = 0.1
  logfc.threshold = 0.15

  se.fltrd = se
  # genes that are differentially expressed in one cluster compared to all other spots
  bpparam = MulticoreParam(workers = 10)
  markers = bplapply(levels(se.fltrd$seurat_clusters), function(cl) {
    
    # old log2FC calculation works better on our data,
    # probably because there is no bias with respect to cluster size then
    cl.markers = FindMarkers(se.fltrd, cl, min.pct = min.pct,
                             logfc.threshold = logfc.threshold,
                             only.pos = F, print.bar = FALSE, test.use = "wilcox",
                             mean.fxn = function(x) {
                               return(log(x = rowMeans(x = expm1(x = x)) + 1, base =2))
                             } )

    cl.markers$cluster = cl
    cl.markers$gene = rownames(cl.markers)
    return(cl.markers)
  }, BPPARAM = bpparam)

  markers.wlcxn = dplyr::bind_rows(markers) %>% dplyr::select(gene, cluster, everything())
  markers.sign = subset(markers.wlcxn, p_val_adj < dgea.pvalue)
  table(markers.wlcxn$cluster)
  length(unique(markers.wlcxn$gene))
  table(markers.sign$cluster)

  # Same results but not parallelized
  # markers.c = Seurat::FindAllMarkers(se.fltrd, min.pct = 0.5, only.pos = F, print.bar = FALSE)
  # markers.c.sign = subset(markers.c, p_val_adj < dgea.pvalue)
  # table(markers.c.sign$cluster)

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Enrichment
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  ora.pvalue = 0.01

  markers.sign.up = subset(markers.sign, avg_log2FC > 0)
  table(markers.sign.up$cluster)

  gene.df = bitr(markers.sign.up$gene, fromType = "SYMBOL", toType = c("ENTREZID"), OrgDb = org.Hs.eg.db)
  markers.sign.up$ENTREZ = gene.df$ENTREZID[match(markers.sign.up$gene, gene.df$SYMBOL)]
  markers.entrez = markers.sign.up[!is.na(markers.sign.up$ENTREZ), ]
  markers.entrez = split(markers.entrez, markers.entrez$cluster)
  markers.entrez = lapply(markers.entrez, function(x){as.character(x$ENTREZ)})
  lengths(markers.entrez)

  universe = bitr(rownames(se), fromType = "SYMBOL", toType = c("ENTREZID"), OrgDb = org.Hs.eg.db)
  universe = unique(universe$ENTREZID)

  res.cP.cc.go = compareCluster(
    geneCluster   = markers.entrez,
    universe = universe,
    fun           ="enrichGO",
    OrgDb         ="org.Hs.eg.db",
    ont           = "BP",
    pAdjustMethod = "BH",
    pvalueCutoff  = ora.pvalue,
    readable      = T
  )

  # dotplot(res.cP.cc.go)
  res.cP.cc.go.sim = simplify(res.cP.cc.go)

  # At least 5 genes must be enriched in the GO Terms
  res = data.frame(res.cP.cc.go.sim@compareClusterResult)
  res = res[res$Count >= 5, ]
  res = split(res, res$Cluster)

  # The top 10 enriched GO Terms for each cluster
  tops.l = lapply(res, function(x){
    x = x[order(x$p.adjust, decreasing = F), ]
    x = head(x, 10)
    x
  })

  tops.l = tops.l[sapply(tops.l, function(x) dim(x)[1]) > 0]

  # E.g. column in dataframe: IL2/APA/PMEL -> make list: keys are the cluster and
  # GO Term, value is a vector with Gene Symbols
  tops.l.ids = list()
  for (i in names(tops.l)) {
    print(i)
    for (j in 1:nrow(tops.l[[i]])) {
      tops.l.ids[[i]][[ tops.l[[i]]$ID[j] ]] = str_split(tops.l[[i]]$geneID[j], "/")[[1]]
    }
  }

  # Calculate the Overall expression of the genes in the GO terms (for each cluster)
  tops.l.oe = list()
  i = 5
  for (i in names(tops.l.ids)) {
    print(i)
    q = tops.l.ids[[i]]

    oe = Seurat::AddModuleScore(se, features = q, name = gsub(":", ".", names(q)),  assay = "Spatial", search = T)
    pd = oe@meta.data
    pd = pd[, grepl("GO.", colnames(pd)), drop = F]
    colnames(pd) = str_sub(colnames(pd), 1, nchar(colnames(pd))-1)
    if (length(colnames(pd)) > 9) {
      colnames(pd)[10:length(colnames(pd))] = str_sub(colnames(pd)[10:length(colnames(pd))], 1, nchar(colnames(pd)[10:length(colnames(pd))])-1)
    }
    tops.l.oe[[i]] = pd
  }

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Save
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  saveRDS(
    list(
      cluster.marker.wlcxn = markers.wlcxn, cl.res = cl.res, dgea.pvalue = dgea.pvalue,
      res.cP.cc.go = res.cP.cc.go, res.cP.cc.go.sim = res.cP.cc.go.sim, ora.pvalue = ora.pvalue,
      tops.l.oe = tops.l.oe
    ),
    file = file.path(work.dir, "07_cluster_markers.rds")
  )
}
