# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# INFO:
# Analyse the clustering generated by a specific resolution.
# Take:
#   06_seurat.rds
#   05_seurat_deconv_results.rds
# Store:
#   09_seurat.rds
#   09_NICHES_LRDE_res.rds
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Packages
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
library("Seurat")
library("yaml")
library("tidyverse")
library("reshape2")
library("robustbase")
library("semla")
library("mixtools")

library("NICHES")

library("liana")

library("sctransform")

# collection of important functions
source("code/helper/FG_helper_NICHES.R")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Important functions section
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Significance threshold (after p.value correction)
p.signif = 0.05

# Addendum: The whole model below assumes that there is a background of
# non-tumor spots with scores around 0! We noticed this prerequisite
# violated in the pozniak et al. samples (lymph node, high tumor content).
# try fitting 3-component equal variance mixture models
# (10 different tries and take the one with best final loglikelihood)
# this usually does a good job at approximating the key components
# there's usually a sharp peak at ~0 that is hard to model,
# so we add this afterwards and relax the model again afterwards
# then we can sum up all background gaussians and compute the cutoff
# we could also exclude "very negative" scores as outliers, but we usually don't need to
calculate.cutoffs.for.tumor <- function(.se, scorename,
                                        min.val.for.mixture = NA,
                                        tries = 10) {
  vals = .se[[scorename]][,1]
  if (!(is.na(min.val.for.mixture))){
    vals = vals[vals >= min.val.for.mixture]
  }
  # using multiple restarts here since models occasionally collapse weirdly
  # eps of 0.0001 is completely sufficient since we deal with log-likelihoods
  # in the hundreds to thousands range
  models = lapply(seq_len(tries), function(i){
    tryCatch(normalmixEM(vals, k = 3, eps = 1e-4,
                         sd.constr = c("a", "a", "a"),  # 3 equal variance components
                         lambda = 1, mu = c(-0.1, 0., 0.3)), # lambda and mu are just initial values
             error = function(e)list(error = e, loglik = -Inf))
  })
  models = models[order(sapply(models, function(r)r$loglik), decreasing = T)]
  model.raw = models[[1]]
  # if all fits fail, print a helpful warning and raise the first error again
  if ("error" %in% names(model.raw)) {
    warning(paste("All", tries, "model fittings failed, here is one error:"))
    stop(model.raw$error)
  }
  # compute the peak location
  vals_sub = vals[vals >= -0.2]
  dens = density(vals, bw = "sj", adjust = 2.)
  peak_xs = dens$x[(dens$x >= -0.2) & (dens$x <= 0.2)]
  peak_ys = dens$y[(dens$x >= -0.2) & (dens$x <= 0.2)]
  peakloc = peak_xs[which.max(peak_ys)]
  # add sharply peaked component at the peak normally observed around 0
  # slightly sharpen, relax roughly with high eps
  model.augmented = normalmixEM(vals, maxit = 100, eps = 1,
                                lambda = c(0.2, model.raw$lambda*0.8),
                                sigma = c(0.05, model.raw$sigma*0.8),
                                sd.constr = c(NA, "a", "a", "a"),
                                mu = c(peakloc, model.raw$mu))
  # if one of the base components wanders of into high-tumor score regions and
  # the tumor component is lost, we can assume that we have too many components
  # and delete the highest and re-relax
  if (any((model.augmented$mu[2:3] > 0.35) & (model.augmented$lambda[2:3] > 0.02))) {
    model.augmented = normalmixEM(vals, maxit = 100, eps = 1,
                                  lambda = model.augmented$lambda[1:3],
                                  sigma = model.augmented$sigma[1:3],
                                  sd.constr = c(NA, "a", "a"),
                                  mu = model.augmented$mu[1:3])
  }
  # fix components, optimize lambdas completely
  mixture.model = normalmixEM(vals, verb = F, maxit = 100, eps = 1e-3,
                              lambda = model.augmented$lambda,
                              sigma = model.augmented$sigma,
                              sd.constr = model.augmented$sigma,
                              mu = model.augmented$mu,
                              mean.constr = model.augmented$mu)

  t <- seq(min(vals)-0.2, max(vals)+0.2, len=300)
  malmask = mixture.model$mu == max(mixture.model$mu)
  # the first positive value at which the posterior probability of the tumor gaussian
  # exceeds the combined posterior probability of the background mixture
  mixture.model.cutoff = t[which.max((t>0) & (dnormmixt(t, mixture.model$lambda[malmask], mixture.model$mu[malmask], mixture.model$sigma[malmask]) >=
                                                dnormmixt(t, mixture.model$lambda[!malmask], mixture.model$mu[!malmask], mixture.model$sigma[!malmask])))]

  res = list(
    mixture.model.cutoff = mixture.model.cutoff,
    mixture.model.applied = T,
    mixture.model=mixture.model
  )
  return(res)
}

# as weird as it is, I'll keep using "True" and "False" for consistency
capitalizefirst <- function(x){paste(toupper(substring(x, 1, 1)),
                                     tolower(substring(x, 2)),
                                     sep = "")}

# filter a list of values for cutoffs
# assumes all numeric entries are possible cutoffs
filter.cutoffs <- function(x){x[sapply(x, is.numeric)] }

# using a prefilter (deconv) and a cutoff model for genesets
assign.positives <- function(se, scorename,
                             cutoff.model, prefilter,
                             add.as.string = T){
  vals = se[[scorename]]
  cutoffs = filter.cutoffs(cutoff.model)
  chosen.threshold = max(unlist(cutoffs))
  model.positives = vals[,1] >= chosen.threshold
  names(model.positives) = colnames(se)

  # added prefiltering by deconvolution results
  names(prefilter) = colnames(se)

  positives = (model.positives & prefilter)

  if (add.as.string) {
    res = capitalizefirst(paste(positives))
  } else {
    res = positives
  }
  return(res)
}

# estimate background distribution with median and scale estimator
# (e.g. Qn from robustbase) and assign points as positive that are significantly
# far away from the background distribution
# (assuming approximately gaussian shape of the background distribution)
# can skip background modelling if assumptions are likely violated
# bg.cutoff.skip is applied then, set to something very conservative like 0.033
calculate.cutoffs.for.immune.fdr.corrected <- function(se, scorename, method = "BH",
                                                       location = median, scale = Qn,
                                                       prefilter, skip_bg_estim = F,
                                                       bg.cutoff.skip = 1/30) {
  vals = se[[scorename]][,1]
  loc = location(vals)
  scl = scale(vals)
  robust.zscores = (vals-loc)/scl
  robust.zscores.prefiltered = robust.zscores[prefilter]
  robust.pvals = sort(pnorm(robust.zscores.prefiltered, lower.tail = F))
  robust.pvals.adj = p.adjust(robust.pvals, method = method)
  lastpos = last(which(robust.pvals.adj<p.signif))
  p.threshold = robust.pvals[lastpos]
  fdr.corrected.background.cutoff = if (!skip_bg_estim) {
    loc + scl*(qnorm(p.threshold, lower.tail = F))
  } else {bg.cutoff.skip}

  res = list(
    fdr.corrected.background.cutoff = fdr.corrected.background.cutoff,
    background.model.applied = !skip_bg_estim,
    background.distr.model = list(location = loc, scale = scl)
  )
  return(res)
}

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# First: prep LRI based on marker gene scores
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

ref_collapsing_file = "assets/single_cell_reference/cell_type_state_matching.tsv"
celltype_collapsing = read_tsv(ref_collapsing_file)

sc_ref_markers = readRDS("data/sc_markers_Stubenvoll_Schmidt_2025.rds")

manifest = yaml.load_file("assets/manifest.yaml")
good_samples = setdiff(c(manifest$samples, manifest$external_samples), manifest$rejected_samples)
random_seed = 02082025

# load once at the start, prepare if necessary (briefly loads seurat objects,
# looks for genes and searches updates for LRI genes not in any of out samples)
liana_nichenet_combined_db = get_combined_lr_dbs()

for (sample_id in good_samples) {

  # The distinction between background and tumor spots based on a mixture model
  # does not work for samples that are almost completely composed of tumor tissue,
  # which is a considerable issue for the Pozniak samples. Therefore, we decided
  # to disable that part and for the external samples
  is_lymph_node = sample_id %in% manifest$external_samples

  is_nevus = sample_id %in% manifest$naevus_samples
  set.seed(random_seed)

  print(paste("LRI from deconvolution - Active sample is now:", sample_id))
  sample_manifest = manifest[[sample_id]]
  work.dir = file.path(manifest$workdata_parent, sample_manifest$workdata)

  se = readRDS(file.path(work.dir, "06_seurat.rds"))
  se$seurat_clusters = se[[paste0("SCT_snn_res.", sample_manifest$seurat_clustering_resolution)]]
  Idents(se) = "seurat_clusters"
  obj = readRDS(file.path(work.dir, "05_seurat_deconv_results.rds"))
  CARD_obj_broad = obj$CARD_obj_broad
  CARD_obj_medium = obj$CARD_obj_medium
  CARD_obj_fine = obj$CARD_obj_fine

  # decon
  sum_types_list_broad = lapply(setNames(nm=unique(celltype_collapsing$sum_type)), function(ct){
    unique(celltype_collapsing[celltype_collapsing$sum_type==ct,]$celltype_broad)
  })
  prop_summed_broad = tibble(!!!lapply(sum_types_list_broad, function(cts){
    if (length(cts)>1)
    {
      rowSums(CARD_obj_broad@Proportion_CARD[,cts])
    } else {
      CARD_obj_broad@Proportion_CARD[,cts]
    }
  })) %>% as.data.frame()
  rownames(prop_summed_broad) = rownames(CARD_obj_broad@Proportion_CARD)
  colnames(prop_summed_broad) = paste0("CARD_broad_", colnames(prop_summed_broad))
  se = AddMetaData(se, prop_summed_broad)

  # add results from deconvolution with medium fine reference annotation
  sum_types_list_medium = lapply(setNames(nm=unique(celltype_collapsing$sum_type)), function(ct){
    unique(celltype_collapsing[celltype_collapsing$sum_type==ct,]$celltype_medium)
  })
  prop_summed_medium = tibble(!!!lapply(sum_types_list_medium, function(cts){
    if (length(cts)>1)
    {
      rowSums(CARD_obj_medium@Proportion_CARD[,cts])
    } else {
      CARD_obj_medium@Proportion_CARD[,cts]
    }
  })) %>% as.data.frame()
  rownames(prop_summed_medium) = rownames(CARD_obj_medium@Proportion_CARD)
  colnames(prop_summed_medium) = paste0("CARD_medium_", colnames(prop_summed_medium))
  se = AddMetaData(se, prop_summed_medium)

  # add results from deconvolution with finely annotated reference
  sum_types_list_fine = lapply(setNames(nm=unique(celltype_collapsing$sum_type)), function(ct){
    unique(celltype_collapsing[celltype_collapsing$sum_type==ct,]$celltype)
  })
  prop_summed_fine = tibble(!!!lapply(sum_types_list_fine, function(cts){
    if (length(cts)>1)
    {
      rowSums(CARD_obj_fine@Proportion_CARD[,cts])
    } else {
      CARD_obj_fine@Proportion_CARD[,cts]
    }
  })) %>% as.data.frame()
  rownames(prop_summed_fine) = rownames(CARD_obj_fine@Proportion_CARD)
  colnames(prop_summed_fine) = paste0("CARD_fine_", colnames(prop_summed_fine))
  se = AddMetaData(se, prop_summed_fine)

  for (nm in names(sum_types_list_fine)) {
    # calculate means of broad and medium, fine is rather instable in our samples
    meta.subs = se@meta.data[paste0(c("CARD_broad_", "CARD_medium_"), nm)]
    se[[paste0("CARD_decon_mean_", nm)]] = rowMeans(meta.subs, na.rm = T)
  }

  celltype.pct.threshold = 0.1
  se.tmp = se

  t.prefilter = se.tmp$`CARD_decon_mean_T/NK_cells` >= celltype.pct.threshold
  t.model = calculate.cutoffs.for.immune.fdr.corrected(se, scorename = "T.cells_logcounts",
                                                       prefilter = t.prefilter,
                                                       skip_bg_estim = is_lymph_node)
  Misc(se, "t.model") = t.model
  se.tmp$T.positive = assign.positives(se.tmp, scorename =  "T.cells_logcounts",
                                       cutoff.model = t.model,
                                       prefilter = t.prefilter)


  nk.prefilter = se.tmp$`CARD_decon_mean_T/NK_cells` >= celltype.pct.threshold
  nk.model = calculate.cutoffs.for.immune.fdr.corrected(se, scorename = "NK.cells_logcounts",
                                                        prefilter = nk.prefilter,
                                                        skip_bg_estim = is_lymph_node)
  Misc(se, "nk.model") = nk.model
  se.tmp$NK.positive = assign.positives(se.tmp, scorename =  "NK.cells_logcounts",
                                        cutoff.model = nk.model,
                                        prefilter = nk.prefilter)

  b.prefilter = se.tmp$`CARD_decon_mean_B/Plasma_cells` >= celltype.pct.threshold
  b.model = calculate.cutoffs.for.immune.fdr.corrected(se, scorename = "B.cells_logcounts",
                                                       prefilter = b.prefilter,
                                                       skip_bg_estim = is_lymph_node)
  Misc(se, "b.model") = b.model
  se.tmp$B.positive = assign.positives(se.tmp, scorename =  "B.cells_logcounts",
                                       cutoff.model = b.model,
                                       prefilter = b.prefilter)


  macro.prefilter = se.tmp$CARD_decon_mean_Macrophages >= celltype.pct.threshold
  macro.model = calculate.cutoffs.for.immune.fdr.corrected(se,
                                                           scorename = "macrophages.and.dendritic.cells_logcounts",
                                                           prefilter = macro.prefilter,
                                                           skip_bg_estim = is_lymph_node)
  Misc(se, "macro.model") = macro.model
  se.tmp$Macrophage.positive = assign.positives(se.tmp,
                                                scorename =  "macrophages.and.dendritic.cells_logcounts",
                                                cutoff.model = macro.model,
                                                prefilter = macro.prefilter)

  se.tmp$IMMUNE.positive = ifelse((se.tmp$T.positive=="True") | (se.tmp$NK.positive=="True"), "True", "False")

  kera.prefilter = se.tmp$CARD_decon_mean_Keratinocytes >= celltype.pct.threshold
  kera.model = calculate.cutoffs.for.tumor(se, scorename = "keratinocytes_logcounts")
  Misc(se, "kera.model") = kera.model
  se.tmp$Keratinocyte.positive = assign.positives(se.tmp,
                                                  scorename =  "keratinocytes_logcounts",
                                                  cutoff.model = kera.model,
                                                  prefilter = kera.prefilter)

  # for the external lymph node samples, use only the deconvolution results
  # and overwrite model to set the threshold on the score to something small
  # to be very conservative (0.05, which is well within background for normal samples)
  # and not the usual background modelling, since it fails if most/all of the
  # sample is tumor.
  # Effectively, mark all spots as positive that have a non-negative tumor score
  # and the deconvolution algorithm says its a tumor spot

  mal.prefilter = se.tmp$CARD_decon_mean_Melanocytic_cells >= celltype.pct.threshold
  mal.model = calculate.cutoffs.for.tumor(se, scorename = "melanocytes.malignant.cells_logcounts")
  if (is_lymph_node) {
    mal.model.fallback = list(mixture.model.cutoff = 1/30,
                              mixture.model.applied = F,
                              mixture.model = mal.model$mixture.model)
    Misc(se, "mal.model") = mal.model.fallback
    se.tmp$TUMOR.positive = assign.positives(se.tmp,
                                             scorename =  "melanocytes.malignant.cells_logcounts",
                                             cutoff.model = mal.model.fallback,
                                             prefilter = mal.prefilter)
  } else {
    Misc(se, "mal.model") = mal.model
    se.tmp$TUMOR.positive = assign.positives(se.tmp,
                                             scorename =  "melanocytes.malignant.cells_logcounts",
                                             cutoff.model = mal.model,
                                             prefilter = mal.prefilter)
  }

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Main definition of immune-positive spots
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  ## selection strategy: select tumor spots over or adjacent to immune spots,
  ## as well as immune spots over or adjacent to tumor spots as active region
  # tumor close to immune first
  Idents(se.tmp) = "IMMUNE.positive"
  # need to catch the case that there are no positive spots, then RegionNeighbors throws
  if (any(se.tmp$IMMUNE.positive=="True")) {
    se.tmp = RegionNeighbors(se.tmp, mode = "all_inner_outer", verbose = F,
                             column_name = "IMMUNE.positive", column_labels = "True")
  } else {
    se.tmp$nb_to_True = NA
  }
  se.tmp[["TUMOR.active"]] = ifelse(is.na(se.tmp$nb_to_True), "False", se.tmp$TUMOR.positive)
  # immune close to tumor now
  Idents(se.tmp) = "TUMOR.positive"
  # need to catch the case that there are no positive spots, then RegioNeighbors throws
  if (any(se.tmp$TUMOR.positive=="True")) {
    se.tmp = RegionNeighbors(se.tmp, mode = "all_inner_outer", verbose = F,
                             column_name = "TUMOR.positive", column_labels = "True")
  } else {
    se.tmp$nb_to_True = NA
  }
  se.tmp[["IMMUNE.active"]] = ifelse(is.na(se.tmp$nb_to_True), "False", se.tmp$IMMUNE.positive)
  # join both active sets
  # uses named instead of True/False because that's clearer later in the diff-LR test section
  ## changed this to include all inactive (non-neighboring) spots to compare against it
  se.tmp[["active.region"]] = ifelse(se.tmp$IMMUNE.active == "True", "Interfacing spots",
                                     ifelse(se.tmp$TUMOR.active == "True", "Interfacing spots",
                                            ifelse(se.tmp$IMMUNE.positive == "True", "Non-interfacing tumor/immune spots",
                                                   ifelse(se.tmp$TUMOR.positive == "True", "Non-interfacing tumor/immune spots",
                                                          "Background"))))
  # add annotations
  se.tmp[["IMMUNE.and.TUMOR"]] = ifelse(se.tmp[["IMMUNE.active"]] == "True" & se.tmp[["TUMOR.active"]] == "True", "True", "False")
  se.tmp[["active.region.annotated"]] = ifelse(se.tmp[["IMMUNE.and.TUMOR"]] == "True", "Interfacing double-positive spots",
                                               ifelse(se.tmp[["IMMUNE.active"]]    == "True", "Interfacing immune-positive spots",
                                                      ifelse(se.tmp[["TUMOR.active"]]     == "True", "Interfacing tumor-positive spots",
                                                             ifelse(se.tmp[["IMMUNE.positive"]]    == "True", "Non-interfacing immune-positive spots",
                                                                    ifelse(se.tmp[["TUMOR.positive"]]     == "True", "Non-interfacing tumor-positive spots",
                                                                           "Double-negative spots")))))

  # copy relevant
  se[["T.positive"]] = se.tmp[["T.positive"]]
  se[["NK.positive"]] = se.tmp[["NK.positive"]]
  se[["B.positive"]] = se.tmp[["B.positive"]]
  se[["Macrophage.positive"]] = se.tmp[["Macrophage.positive"]]
  se[["Keratinocyte.positive"]] = se.tmp[["Keratinocyte.positive"]]

  se[["TUMOR.positive"]] = se.tmp[["TUMOR.positive"]]
  se[["IMMUNE.positive"]] = se.tmp[["IMMUNE.positive"]]
  se[["active.region"]] = se.tmp[["active.region"]]
  se[["active.region.annotated"]] = se.tmp[["active.region.annotated"]]

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Run LRI using NICHES if feasible
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  ######
  # We need to check if we found a border region at all.
  # In some cases, there are very few immune cells or the immune cells
  # are not directly bordering the active region of the tumor.
  # In those cases, we can't do any meaningful comparisons according to our strategy here, so we skip the rest.
  # We require at least 5 tumor and 5 immune spots.
  # We also require at least 5 spots in the active border region and at least 5 inactive spots.
  #####

  has.proper.border = (sum(se[["active.region"]] == "Non-interfacing tumor/immune spots") >= 5) &
    (sum(se[["active.region"]] == "Interfacing spots") >= 5) &
    (sum(se[["TUMOR.positive"]] == "True") >= 5) &
    (sum(se[["IMMUNE.positive"]] == "True") >= 5)

  Misc(se, "has_sufficient_tumor_immune_border") = has.proper.border

  NICHES_result = NULL

  # run NICHES with patches on combined database
  # liana_nichenet_combined_db already loaded at the beginning once
  lr_db = liana_nichenet_combined_db %>% select(from, to) %>% distinct() # "from" is the ligand and "to" the receptor

  # normalized data
  DefaultAssay(se) = "Spatial"
  Idents(se) = "seurat_clusters"
  NICHES_result_normalized = do_NICHES_with_patches(se = se, lr_db = lr_db,
                                                    assay = "Spatial",
                                                    conserved.metadata = "seurat_clusters")
  # logcounts
  DefaultAssay(se) = "RNA_logcounts"
  Idents(se) = "seurat_clusters"
  NICHES_result_logcounts = do_NICHES_with_patches(se = se, lr_db = lr_db,
                                                   assay = "RNA_logcounts",
                                                   conserved.metadata = "seurat_clusters")

  NICHES_result = list(normalized = NICHES_result_normalized, logcounts = NICHES_result_logcounts)

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Save Seurat obj + NICHES result, DE results saved separately
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  saveRDS(
    list(se = se, NICHES_result = NICHES_result),
    file = file.path(work.dir, "09_seurat.rds")
  )

  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # Run enrichment tests, save separately because aggregation doesn't need full objects
  # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  if (!(has.proper.border)) {
    print("Sample has no insufficient Tumor-Immune-Border spots, no enrichment computed.")
  } else {
    ### TODO:
    ###   think about diff_mean_test (should we shuffle IMMUNE.positive and TUMOR.positive and recompute active and inactive spots each time??)
    ###   think about test on edges

    # DE
    # new version, using a nicer Non-parametric differential expression test for sparse non-negative data from sctransform package

    se.tmp = add_NICHES_to_se(se, NICHES_result$normalized)

    norm_border.markers.ntc = lr_de_spots(se = se.tmp, group.by = "active.region",
                                          active.groups = "Interfacing spots",
                                          background.groups = "Non-interfacing tumor/immune spots",
                                          assay = "NeighborhoodToCell", mean_type = "arithmetic",
                                          R = 9999, log2FC_th = log2(1.1))

    norm_border.markers.ctn = lr_de_spots(se = se.tmp, group.by = "active.region",
                                          active.groups = "Interfacing spots",
                                          background.groups = "Non-interfacing tumor/immune spots",
                                          assay = "CellToNeighborhood", mean_type = "arithmetic",
                                          R = 9999, log2FC_th = log2(1.1))

    se.tmp = add_NICHES_to_se(se, NICHES_result$logcounts)

    logc_border.markers.ntc = lr_de_spots(se = se.tmp, group.by = "active.region",
                                          active.groups = "Interfacing spots",
                                          background.groups = "Non-interfacing tumor/immune spots",
                                          assay = "NeighborhoodToCell", mean_type = "arithmetic",
                                          R = 9999, log2FC_th = log2(1.1))

    logc_border.markers.ctn = lr_de_spots(se = se.tmp, group.by = "active.region",
                                          active.groups = "Interfacing spots",
                                          background.groups = "Non-interfacing tumor/immune spots",
                                          assay = "CellToNeighborhood", mean_type = "arithmetic",
                                          R = 9999, log2FC_th = log2(1.1))

    saveRDS(list(logcounts = list(border.markers.NeighborhoodToCell = logc_border.markers.ntc,
                                  border.markers.CellToNeighborhood = logc_border.markers.ctn),
                 normalized = list(border.markers.NeighborhoodToCell = norm_border.markers.ntc,
                                   border.markers.CellToNeighborhood = norm_border.markers.ctn)),
            file = file.path(work.dir, "09_NICHES_LRDE_res.rds"))

  }
}
